begin;
insert into symbols (symbol, company_name, exchange) select 'AMJ', 'Alerian MLP Index ETN', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'AMJ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'AMLP', 'Alerian MLP ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'AMLP' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'ASHR', 'db X-trackers Harvest CSI 300 China A-Shares Fund', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'ASHR' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'BKLN', 'Senior Loan Portfolio', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'BKLN' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'DBEF', 'MSCI EAFE Hedged Equity Fund', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'DBEF' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'DGAZ', '3x Inverse Natural Gas ETN', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'DGAZ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'DIA', 'Dow Jones Industrial Average ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'DIA' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'DUST', 'Daily Gold Miners Bear 3x Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'DUST' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'DXJ', 'Japan Hedged Equity Fund', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'DXJ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EEM', 'iShares MSCI Emerging Markets ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EEM' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EFA', 'iShares MSCI EAFE ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EFA' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EPI', 'India Earnings Fund', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EPI' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'ERX', 'Daily Energy Bull 3X Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'ERX' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWA', 'MSCI Australia ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWA' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWC', 'iShares MSCI Canada ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWC' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWG', 'iShares MSCI Germany ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWG' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWH', 'iShares MSCI Hong Kong ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWH' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWI', 'iShares MSCI Italy Capped ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWI' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWJ', 'iShares MSCI Japan ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWJ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWT', 'iShares MSCI Taiwan ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWT' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWU', 'iShares MSCI United Kingdom ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWU' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWW', 'iShares MSCI Mexico Capped ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWW' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWY', 'iShares MSCI South Korea Capped ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWY' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EWZ', 'iShares MSCI Brazil Capped ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EWZ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'EZU', 'iShares MSCI EMU ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'EZU' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'FAS', 'Daily Financial Bull 3X Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'FAS' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'FAZ', 'Daily Financial Bear 3X Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'FAZ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'FEZ', 'SPDR Euro STOXX 50 ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'FEZ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'FV', 'Dorsey Wright Focus 5 ETF', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FV' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FXI', 'iShares China Large-Cap ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'FXI' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'GDX', 'Market Vectors TR Gold Miners', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'GDX' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'GDXJ', 'Market Vectors Junior Gold Miners ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'GDXJ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'GLD', 'SPDR Gold Trust', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'GLD' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'HEDJ', 'Europe Hedged Equity Fund', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'HEDJ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'HYG', 'iShares iBoxx $ High Yield Corporate Bond ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'HYG' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'IAU', 'COMEX Gold Trust', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'IAU' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'IEMG', 'Core MSCI Emerging Markets ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'IEMG' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'INDA', 'MSCI India Index Fund', 'BATS' where not exists (select 1 from symbols where symbol = 'INDA' and exchange = 'BATS');
insert into symbols (symbol, company_name, exchange) select 'ITB', 'iShares U.S. Home Construction ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'ITB' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'IVV', 'Core S&P 500 ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'IVV' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'IWM', 'iShares Russell 2000 ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'IWM' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'IYR', 'iShares U.S. Real Estate ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'IYR' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'JDST', 'Daily Junior Gold Miners Index Bear 3x Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'JDST' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'JNK', 'SPDR Barclays Capital High Yield Bond ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'JNK' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'JNUG', 'Daily Junior Gold Miners Index Bull 3x Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'JNUG' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'KRE', 'SPDR S&P Regional Banking ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'KRE' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'LQD', 'iShares iBoxx $ Investment Grade Corporate Bond ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'LQD' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'NUGT', 'Daily Gold Miners Bull 3x Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'NUGT' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'OIH', 'Market Vectors Oil Services ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'OIH' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'OIL', 'S&P GSCI Crude Oil Tot Ret Idx ETN', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'OIL' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'QID', 'UltraShort QQQ', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'QID' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'QLD', 'Ultra QQQ', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'QLD' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'QQQ', 'QQQ', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'QQQ' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'RSX', 'Market Vectors Russia ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'RSX' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'SDS', 'UltraShort S&P500', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'SDS' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'SH', 'Short S&P500', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'SH' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'SLV', 'Silver Trust', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'SLV' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'SMH', 'Market Vectors Semiconductor ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'SMH' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'SPXS', 'Daily S&P 500 Bear 3x Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'SPXS' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'SPXU', 'UltraPro Short S&P500', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'SPXU' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'SPY', 'SPDR S&P 500', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'SPY' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'SQQQ', 'UltraPro Short QQQ', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SQQQ' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SSO', 'Ultra S&P500', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'SSO' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'SVXY', 'Short VIX Short-Term Futures ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'SVXY' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'TBT', 'UltraShort Barclays 20+ Year Treasury', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'TBT' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'TLT', '20+ Year Treasury Bond ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'TLT' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'TNA', 'Daily Small Cap Bull 3X Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'TNA' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'TQQQ', 'UltraPro QQQ', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TQQQ' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'TVIX', 'Daily 2x VIX Short-Term ETN', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TVIX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'TZA', 'Daily Small Cap Bear 3X Shares', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'TZA' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'UCO', 'Ultra DJ-UBS Crude Oil', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'UCO' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'UGAZ', '3x Long Natural Gas ETN', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'UGAZ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'UNG', 'United States Natural Gas Fund LP', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'UNG' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'UPRO', 'UltraPro S&P 500', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'UPRO' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'USO', 'United States Oil Fund', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'USO' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'UUP', 'DB USD Index Bullish', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'UUP' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'UVXY', 'Ultra VIX Short-Term Futures ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'UVXY' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'UWTI', '3x Long Crude ETN', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'UWTI' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'VEA', 'Europe Pacific', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'VEA' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'VEU', 'FTSE All World Ex US ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'VEU' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'VGK', 'FTSE Europe ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'VGK' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'VIXY', 'VIX Short-Term Futures ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'VIXY' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'VNQ', 'REIT ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'VNQ' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'VOO', 'S&P 500 ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'VOO' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'VTI', 'Total Stock Market ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'VTI' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'VWO', 'Emerging Markets ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'VWO' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'VXX', 'S&P 500 VIX Short-Term Futures ETN', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'VXX' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XHB', 'SPDR Homebuilders ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XHB' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XIV', 'Daily Inverse VIX Short-Term ETN', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'XIV' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'XLB', 'Materials Select Sector SPDR', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XLB' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XLE', 'Energy Select Sector SPDR', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XLE' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XLF', 'Financial Select Sector SPDR', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XLF' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XLI', 'Industrial Select Sector SPDR', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XLI' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XLK', 'Technology Select Sector SPDR', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XLK' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XLP', 'Consumer Staples Select Sector SPDR', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XLP' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XLU', 'Utilities Select Sector SPDR', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XLU' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XLV', 'Health Care Select Sector SPDR', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XLV' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XLY', 'Consumer Discretionary Select Sector SPDR', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XLY' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XME', 'SPDR S&P Metals & Mining ETF', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XME' and exchange = 'NYSE ArcaSM');
insert into symbols (symbol, company_name, exchange) select 'XOP', 'SPDR S&P Oil & Gas Explor & Product', 'NYSE ArcaSM' where not exists (select 1 from symbols where symbol = 'XOP' and exchange = 'NYSE ArcaSM');
commit;
