begin;
insert into symbols (symbol, company_name, exchange) select 'AAL', 'American Airlines Group Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AAL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AAPL', 'Apple Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AAPL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ADBE', 'Adobe Systems Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ADBE' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ADI', 'Analog Devices Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ADI' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ADP', 'Automatic Data Processing Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ADP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ADSK', 'Autodesk Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ADSK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AKAM', 'Akamai Technologies Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AKAM' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ALTR', 'Altera Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ALTR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ALXN', 'Alexion Pharmaceuticals Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ALXN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AMAT', 'Applied Materials Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AMAT' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AMGN', 'Amgen Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AMGN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AMZN', 'Amazon.com Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AMZN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ATVI', 'Activision Blizzard Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ATVI' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AVGO', 'Avago Technologies Ltd', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AVGO' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'BBBY', 'Bed Bath & Beyond Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'BBBY' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'BIDU', 'Baidu Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'BIDU' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'BIIB', 'Biogen Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'BIIB' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'BMRN', 'Biomarin Pharmaceutical Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'BMRN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'BRCM', 'Broadcom Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'BRCM' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CA', 'CA Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CELG', 'Celgene Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CELG' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CERN', 'Cerner Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CERN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CHKP', 'Check Point Software Technologies Ltd', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CHKP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CHRW', 'C.H. Robinson Worldwide Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CHRW' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CHTR', 'Charter Communications Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CHTR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CMCSA', 'Comcast Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CMCSA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CMCSK', 'Comcast Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CMCSK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'COST', 'Costco Wholesale Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'COST' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CSCO', 'Cisco Systems Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CSCO' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CTSH', 'Cognizant Technology Solutions Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CTSH' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CTXS', 'Citrix Systems Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CTXS' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'DISCA', 'Discovery Communications Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'DISCA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'DISCK', 'Discovery Communications Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'DISCK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'DISH', 'DISH Network Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'DISH' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'DLTR', 'Dollar Tree Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'DLTR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'EA', 'Electronic Arts', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'EA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'EBAY', 'eBay Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'EBAY' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ESRX', 'Express Scripts Holding Co', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ESRX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'EXPD', 'Expeditors International of Washington Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'EXPD' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'EXPE', 'Expedia Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'EXPE' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FAST', 'Fastenal Co', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FAST' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FB', 'Facebook', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FB' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FISV', 'Fiserv Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FISV' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FOX', '21st Century Fox Class B', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FOX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FOXA', '21st Century Fox Class A', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FOXA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GILD', 'Gilead Sciences Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GILD' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GMCR', 'Keurig Green Mountain Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GMCR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GOOG', 'Google Class C', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GOOG' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GOOGL', 'Google Class A', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GOOGL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GRMN', 'Garmin Ltd', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GRMN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'HSIC', 'Henry Schein Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'HSIC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'INTC', 'Intel Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'INTC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'INTU', 'Intuit Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'INTU' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ILMN', 'Illumina Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ILMN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ISRG', 'Intuitive Surgical Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ISRG' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'JD', 'JD.com Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'JD' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'KLAC', 'KLA-Tencor Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'KLAC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'KHC', 'Kraft Heinz Co', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'KHC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LBTYA', 'Liberty Global PLC', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LBTYA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LBTYK', 'Liberty Global PLC', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LBTYK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LILA', 'Liberty Global PLC', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LILA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LILAK', 'Liberty Global PLC', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LILAK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LLTC', 'Linear Technology Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LLTC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LMCA', 'Liberty Media Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LMCA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LRCX', 'Lam Research Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LRCX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LVNTA', 'Liberty Interactive Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LVNTA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MAR', 'Marriott International Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MAR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MAT', 'Mattel Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MAT' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MDLZ', 'Mondelez International Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MDLZ' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MNST', 'Monster Beverage Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MNST' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MSFT', 'Microsoft Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MSFT' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MU', 'Micron Technology Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MU' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MYL', 'Mylan NV', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MYL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NFLX', 'Netflix Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NFLX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NTAP', 'NetApp Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NTAP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NVDA', 'NVIDIA Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NVDA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NXPI', 'NXP Semiconductors NV', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NXPI' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ORLY', 'O''Reilly Automotive Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ORLY' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'PAYX', 'Paychex Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'PAYX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'PCAR', 'PACCAR Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'PCAR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'PCLN', 'The Priceline Group', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'PCLN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'QCOM', 'Qualcomm Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'QCOM' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'QVCA', 'Liberty Interactive Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'QVCA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'REGN', 'Regeneron Pharmaceuticals Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'REGN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ROST', 'Ross Stores Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ROST' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SBAC', 'SBA Communications Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SBAC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SBUX', 'Starbucks Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SBUX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SIRI', 'Sirius XM Holdings Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SIRI' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SNDK', 'SanDisk Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SNDK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SPLS', 'Staples Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SPLS' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SRCL', 'Stericycle Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SRCL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'STX', 'Seagate Technology PLC', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'STX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SWKS', 'Skyworks Solutions Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SWKS' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SYMC', 'Symantec Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SYMC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'TSCO', 'Tractor Supply Co', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TSCO' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'TSLA', 'Tesla Motors Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TSLA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'TRIP', 'TripAdvisor Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TRIP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'TXN', 'Texas Instruments Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TXN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'VIAB', 'Viacom Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'VIAB' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'VIP', 'VimpelCom Ltd', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'VIP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'VOD', 'Vodafone Group PLC', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'VOD' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'VRSK', 'Verisk Analytics Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'VRSK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'VRTX', 'Vertex Pharmaceuticals Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'VRTX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'WBA', 'Walgreens Boots Alliance Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'WBA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'WDC', 'Western Digital Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'WDC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'WFM', 'Whole Foods Market Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'WFM' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'WYNN', 'Wynn Resorts Ltd', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'WYNN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'XLNX', 'Xilinx Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'XLNX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'YHOO', 'Yahoo Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'YHOO' and exchange = 'NASDAQ OMX');

commit;
