begin;

insert into symbols (symbol, company_name, exchange) select 'MMM', '3M Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'MMM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ACE', 'ACE Limited', 'NYSE' where not exists (select 1 from symbols where symbol = 'ACE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AES', 'AES Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'AES' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AFL', 'AFLAC Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AFL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GAS', 'AGL Resources', 'NYSE' where not exists (select 1 from symbols where symbol = 'GAS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AME', 'AMETEK Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AME' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'T', 'AT&T Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'T' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ABBV', 'AbbVie Inc.', 'NYSE' where not exists (select 1 from symbols where symbol = 'ABBV' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ABT', 'Abbott Laboratories', 'NYSE' where not exists (select 1 from symbols where symbol = 'ABT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ACN', 'Accenture plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ACN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ADBE', 'Adobe Systems Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ADBE' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AAP', 'Advance Auto Parts Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AAP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AET', 'Aetna Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AET' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AMG', 'Affiliated Managers Grp', 'NYSE' where not exists (select 1 from symbols where symbol = 'AMG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'A', 'Agilent Technologies Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'A' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'APD', 'Air Products & Chemicals Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'APD' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ARG', 'Airgas Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ARG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AKAM', 'Akamai Technologies Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AKAM' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AA', 'Alcoa Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ALXN', 'Alexion Pharmaceuticals Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ALXN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ALLE', 'Allegion plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ALLE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AGN', 'Allergan plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AGN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ADS', 'Alliance Data Systems Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'ADS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ALL', 'Allstate Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'ALL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ALTR', 'Altera Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ALTR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MO', 'Altria Group Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'MO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AMZN', 'Amazon.com Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AMZN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AEE', 'Ameren Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'AEE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AAL', 'American Airlines Group Inc.', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AAL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AEP', 'American Electric Power', 'NYSE' where not exists (select 1 from symbols where symbol = 'AEP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AXP', 'American Express Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'AXP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AIG', 'American Intl Group Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AIG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AMT', 'American Tower Corp A', 'NYSE' where not exists (select 1 from symbols where symbol = 'AMT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AMP', 'Ameriprise Financial Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AMP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ABC', 'AmerisourceBergen Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'ABC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AMGN', 'Amgen Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AMGN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'APH', 'Amphenol Corp A', 'NYSE' where not exists (select 1 from symbols where symbol = 'APH' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'APC', 'Anadarko Petroleum Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'APC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ADI', 'Analog Devices Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ADI' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ANTM', 'Anthem Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ANTM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AON', 'Aon plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AON' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'APA', 'Apache Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'APA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AIV', 'Apartment Investment & Mgmt', 'NYSE' where not exists (select 1 from symbols where symbol = 'AIV' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AAPL', 'Apple Inc.', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AAPL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AMAT', 'Applied Materials Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AMAT' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ADM', 'Archer-Daniels-Midland Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'ADM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AIZ', 'Assurant Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AIZ' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AN', 'AutoNation Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AZO', 'AutoZone Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AZO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ADSK', 'Autodesk Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ADSK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ADP', 'Automatic Data Processing', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ADP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AVGO', 'Avago Technologies Ltd', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'AVGO' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'AVB', 'AvalonBay Communities Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'AVB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'AVY', 'Avery Dennison Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'AVY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BBT', 'BB&T Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'BBT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BHI', 'Baker Hughes Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'BHI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BLL', 'Ball Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'BLL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BAC', 'Bank of America Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'BAC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BCR', 'Bard C.R. Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'BCR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BXLT', 'Baxalta Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'BXLT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BAX', 'Baxter Intl Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'BAX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BDX', 'Becton Dickinson & Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'BDX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BBBY', 'Bed Bath & Beyond Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'BBBY' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'BRK/B', 'Berkshire Hathaway B', 'NYSE' where not exists (select 1 from symbols where symbol = 'BRK/B' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BBY', 'Best Buy Co Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'BBY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BIIB', 'Biogen Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'BIIB' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'BLK', 'BlackRock Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'BLK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HRB', 'Block H & R Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HRB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BA', 'Boeing Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'BA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BWA', 'Borgwarner Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'BWA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BXP', 'Boston Properties Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'BXP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BSX', 'Boston Scientific Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'BSX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BMY', 'Bristol-Myers Squibb', 'NYSE' where not exists (select 1 from symbols where symbol = 'BMY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BRCM', 'Broadcom Corp A', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'BRCM' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'BF/B', 'Brown-Forman Corp B', 'NYSE' where not exists (select 1 from symbols where symbol = 'BF/B' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CA', 'CA Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CBG', 'CBRE Group Inc.', 'NYSE' where not exists (select 1 from symbols where symbol = 'CBG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CBS', 'CBS Corp B', 'NYSE' where not exists (select 1 from symbols where symbol = 'CBS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CF', 'CF Industries Holdings', 'NYSE' where not exists (select 1 from symbols where symbol = 'CF' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CHRW', 'CH Robinson Worldwide Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CHRW' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CME', 'CME Group Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CME' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CMS', 'CMS Energy Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'CMS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CNX', 'CONSOL Energy Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'CNX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CSX', 'CSX Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'CSX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CVS', 'CVS Health Corporation', 'NYSE' where not exists (select 1 from symbols where symbol = 'CVS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CVC', 'Cablevision Systems Co A', 'NYSE' where not exists (select 1 from symbols where symbol = 'CVC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'COG', 'Cabot Oil & Gas A', 'NYSE' where not exists (select 1 from symbols where symbol = 'COG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CAM', 'Cameron International Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'CAM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CPB', 'Campbell Soup Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'CPB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'COF', 'Capital One Financial', 'NYSE' where not exists (select 1 from symbols where symbol = 'COF' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CAH', 'Cardinal Health Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'CAH' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KMX', 'Carmax Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'KMX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CCL', 'Carnival Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'CCL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CAT', 'Caterpillar Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'CAT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CELG', 'Celgene Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CELG' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CNP', 'Centerpoint Energy Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'CNP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CTL', 'CenturyLink Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'CTL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CERN', 'Cerner Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CERN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CHK', 'Chesapeake Energy Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'CHK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CVX', 'Chevron Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'CVX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CMG', 'Chipotle Mexican Grill Inc.', 'NYSE' where not exists (select 1 from symbols where symbol = 'CMG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CB', 'Chubb Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'CB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CI', 'Cigna Corporation', 'NYSE' where not exists (select 1 from symbols where symbol = 'CI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'XEC', 'Cimarex Energy Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'XEC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CINF', 'Cincinnati Financial Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CINF' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CTAS', 'Cintas Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CTAS' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CSCO', 'Cisco Systems Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CSCO' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'C', 'Citigroup Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'C' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CTXS', 'Citrix Systems Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CTXS' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CLX', 'Clorox Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'CLX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'COH', 'Coach Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'COH' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KO', 'Coca-Cola Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'KO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CCE', 'Coca-Cola Enterprises', 'NYSE' where not exists (select 1 from symbols where symbol = 'CCE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CTSH', 'Cognizant Tech Solutions Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CTSH' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CL', 'Colgate-Palmolive Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'CL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CPGX', 'Columbia Pipeline Group', 'NYSE' where not exists (select 1 from symbols where symbol = 'CPGX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CMCSA', 'Comcast Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'CMCSA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CMA', 'Comerica Inc (MI)', 'NYSE' where not exists (select 1 from symbols where symbol = 'CMA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CSC', 'Computer Sciences', 'NYSE' where not exists (select 1 from symbols where symbol = 'CSC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CAG', 'ConAgra Foods Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'CAG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'COP', 'ConocoPhillips', 'NYSE' where not exists (select 1 from symbols where symbol = 'COP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ED', 'Consolidated Edison Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ED' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'STZ', 'Constellation Brands Inc A', 'NYSE' where not exists (select 1 from symbols where symbol = 'STZ' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GLW', 'Corning Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'GLW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'COST', 'Costco Wholesale Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'COST' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'CCI', 'Crown Castle Intl Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'CCI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CMI', 'Cummins Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'CMI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DTE', 'DTE Energy Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'DTE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DVA', 'DaVita HealthCare Partners Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'DVA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DHR', 'Danaher Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'DHR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DRI', 'Darden Restaurants Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'DRI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DE', 'Deere & Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'DE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DLPH', 'Delphi Automotive PLC', 'NYSE' where not exists (select 1 from symbols where symbol = 'DLPH' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DAL', 'Delta Air Lines', 'NYSE' where not exists (select 1 from symbols where symbol = 'DAL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'XRAY', 'Dentsply Intl', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'XRAY' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'DVN', 'Devon Energy Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'DVN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DO', 'Diamond Offshore Drilling', 'NYSE' where not exists (select 1 from symbols where symbol = 'DO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DFS', 'Discover Financial Services', 'NYSE' where not exists (select 1 from symbols where symbol = 'DFS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DISCA', 'Discovery Communications Inc A', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'DISCA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'DISCK', 'Discovery Communications Inc C', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'DISCK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'DG', 'Dollar General Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'DG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DLTR', 'Dollar Tree Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'DLTR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'D', 'Dominion Resources Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'D' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DOV', 'Dover Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'DOV' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DOW', 'Dow Chemical', 'NYSE' where not exists (select 1 from symbols where symbol = 'DOW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DPS', 'Dr Pepper Snapple Group', 'NYSE' where not exists (select 1 from symbols where symbol = 'DPS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DUK', 'Duke Energy Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'DUK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DNB', 'Dun & Bradstreet Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'DNB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ETFC', 'E*TRADE Financial Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ETFC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'DD', 'E. I. du Pont de Nemours and Company', 'NYSE' where not exists (select 1 from symbols where symbol = 'DD' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EMC', 'EMC Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'EMC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EOG', 'EOG Resources', 'NYSE' where not exists (select 1 from symbols where symbol = 'EOG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EQT', 'EQT Corporation', 'NYSE' where not exists (select 1 from symbols where symbol = 'EQT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EMN', 'Eastman Chemical Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'EMN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ETN', 'Eaton Corp plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ETN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ECL', 'Ecolab Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ECL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EIX', 'Edison Intl', 'NYSE' where not exists (select 1 from symbols where symbol = 'EIX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EW', 'Edwards Lifesciences Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'EW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EA', 'Electronic Arts', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'EA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'EMR', 'Emerson Electric Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'EMR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ENDP', 'Endo International plc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ENDP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ESV', 'Ensco PLC - CL A', 'NYSE' where not exists (select 1 from symbols where symbol = 'ESV' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ETR', 'Entergy Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'ETR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EFX', 'Equifax Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'EFX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EQIX', 'Equinix Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'EQIX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'EQR', 'Equity Residential', 'NYSE' where not exists (select 1 from symbols where symbol = 'EQR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ESS', 'Essex Property Trust', 'NYSE' where not exists (select 1 from symbols where symbol = 'ESS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EL', 'Estee Lauder Cos.', 'NYSE' where not exists (select 1 from symbols where symbol = 'EL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ES', 'Eversource Energy', 'NYSE' where not exists (select 1 from symbols where symbol = 'ES' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EXC', 'Exelon Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'EXC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EXPE', 'Expedia', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'EXPE' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'EXPD', 'Expeditors Intl of WA Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'EXPD' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ESRX', 'Express Scripts Holding Co.', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ESRX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'XOM', 'Exxon Mobil Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'XOM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FFIV', 'F5 Networks Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FFIV' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FLIR', 'FLIR Systems Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FLIR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FMC', 'FMC Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'FMC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FTI', 'FMC Technologies Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'FTI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FB', 'Facebook Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FB' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FAST', 'Fastenal Co', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FAST' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FDX', 'FedEx Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'FDX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FIS', 'Fidelity National Information', 'NYSE' where not exists (select 1 from symbols where symbol = 'FIS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FITB', 'Fifth Third Bancorp (OH)', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FITB' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FSLR', 'First Solar Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FSLR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FE', 'FirstEnergy Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'FE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FISV', 'Fiserv Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FISV' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FLS', 'Flowserve Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'FLS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FLR', 'Fluor Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'FLR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'F', 'Ford Motor Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'F' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FOSL', 'Fossil Group Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FOSL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'BEN', 'Franklin Resources Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'BEN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FCX', 'Freeport-McMoRan Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'FCX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'FTR', 'Frontier Communications Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FTR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GME', 'GameStop Corp A', 'NYSE' where not exists (select 1 from symbols where symbol = 'GME' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GPS', 'Gap Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'GPS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GRMN', 'Garmin Ltd', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GRMN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GD', 'General Dynamics', 'NYSE' where not exists (select 1 from symbols where symbol = 'GD' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GE', 'General Electric Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'GE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GGP', 'General Growth Properties Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'GGP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GIS', 'General Mills Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'GIS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GM', 'General Motors Company', 'NYSE' where not exists (select 1 from symbols where symbol = 'GM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GPC', 'Genuine Parts Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'GPC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GNW', 'Genworth Financial Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'GNW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GILD', 'Gilead Sciences Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GILD' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GS', 'Goldman Sachs Group Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'GS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GT', 'Goodyear Tire & Rubber Co', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GT' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GOOGL', 'Google Inc A', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GOOGL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GOOG', 'Google Inc C', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GOOG' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'GWW', 'Grainger W.W. Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'GWW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HCA', 'HCA Holdings Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HCA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HCP', 'HCP Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HCP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HAL', 'Halliburton Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'HAL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HBI', 'Hanesbrands Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HBI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HOG', 'Harley-Davidson Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HOG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HAR', 'Harman Intl Industries Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HAR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HRS', 'Harris Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'HRS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HIG', 'Hartford Finl Services Group', 'NYSE' where not exists (select 1 from symbols where symbol = 'HIG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HAS', 'Hasbro Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'HAS' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'HCN', 'Health Care REIT Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HCN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HP', 'Helmerich & Payne Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HSY', 'Hershey Foods Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'HSY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HES', 'Hess Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'HES' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HPQ', 'Hewlett-Packard Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'HPQ' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HD', 'Home Depot Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HD' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HON', 'Honeywell Intl Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HON' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HRL', 'Hormel Foods Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'HRL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DHI', 'Horton D.R. Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'DHI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HSP', 'Hospira Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HSP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HST', 'Host Hotels & Resorts Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HST' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'HCBK', 'Hudson City Bancorp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'HCBK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'HUM', 'Humana Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'HUM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'JBHT', 'Hunt J.B. Transport Services', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'JBHT' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'HBAN', 'Huntington Bancshares (OH)', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'HBAN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ITW', 'Illinois Tool Works Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ITW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'IR', 'Ingersoll-Rand Plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'IR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'INTC', 'Intel Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'INTC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ICE', 'Intercontinental Exchange Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ICE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'IPG', 'Interpublic Group Cos', 'NYSE' where not exists (select 1 from symbols where symbol = 'IPG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'IBM', 'Intl Business Machines Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'IBM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'IFF', 'Intl Flavors & Fragrances', 'NYSE' where not exists (select 1 from symbols where symbol = 'IFF' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'IP', 'Intl Paper Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'IP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'INTU', 'Intuit Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'INTU' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ISRG', 'Intuitive Surgical Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ISRG' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'IVZ', 'Invesco Ltd', 'NYSE' where not exists (select 1 from symbols where symbol = 'IVZ' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'IRM', 'Iron Mountain Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'IRM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'JPM', 'JP Morgan Chase & Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'JPM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'JEC', 'Jacobs Engineering Group Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'JEC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'JNJ', 'Johnson & Johnson', 'NYSE' where not exists (select 1 from symbols where symbol = 'JNJ' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'JCI', 'Johnson Controls Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'JCI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'JOY', 'Joy Global Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'JOY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'JNPR', 'Juniper Networks Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'JNPR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KLAC', 'KLA-Tencor Corporation', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'KLAC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'KSU', 'Kansas City Southern Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'KSU' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'K', 'Kellogg Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'K' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'GMCR', 'Keurig Green Mountain Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'GMCR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'KEY', 'KeyCorp', 'NYSE' where not exists (select 1 from symbols where symbol = 'KEY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KMB', 'Kimberly-Clark', 'NYSE' where not exists (select 1 from symbols where symbol = 'KMB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KIM', 'Kimco Realty Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'KIM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KMI', 'Kinder Morgan Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'KMI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KSS', 'Kohl''s Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'KSS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KR', 'Kroger Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'KR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LB', 'L Brands Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'LB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LLL', 'L-3 Communications Holdings', 'NYSE' where not exists (select 1 from symbols where symbol = 'LLL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LH', 'Lab Corp of America Hldgs', 'NYSE' where not exists (select 1 from symbols where symbol = 'LH' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LRCX', 'Lam Research Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LRCX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LM', 'Legg Mason Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'LM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LEG', 'Leggett & Platt', 'NYSE' where not exists (select 1 from symbols where symbol = 'LEG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LEN', 'Lennar Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'LEN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LUK', 'Leucadia National Corp (NY)', 'NYSE' where not exists (select 1 from symbols where symbol = 'LUK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LVLT', 'Level 3 Communications', 'NYSE' where not exists (select 1 from symbols where symbol = 'LVLT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LLY', 'Lilly Eli & Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'LLY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LNC', 'Lincoln National Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'LNC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LLTC', 'Linear Technology Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'LLTC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'LMT', 'Lockheed Martin', 'NYSE' where not exists (select 1 from symbols where symbol = 'LMT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'L', 'Loews Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'L' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LOW', 'Lowe''s Cos Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'LOW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LYB', 'LyondellBasell Industries N.V.', 'NYSE' where not exists (select 1 from symbols where symbol = 'LYB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MTB', 'M&T Bank Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'MTB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MAC', 'Macerich Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'MAC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'M', 'Macy''s Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'M' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MNK', 'Mallinckrodt plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'MNK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MRO', 'Marathon Oil Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'MRO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MPC', 'Marathon Petroleum Corp.', 'NYSE' where not exists (select 1 from symbols where symbol = 'MPC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MAR', 'Marriott Intl A', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MAR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MMC', 'Marsh & McLennan Companies', 'NYSE' where not exists (select 1 from symbols where symbol = 'MMC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MLM', 'Martin Marietta Materials', 'NYSE' where not exists (select 1 from symbols where symbol = 'MLM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MAS', 'Masco Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'MAS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MA', 'Mastercard Inc A', 'NYSE' where not exists (select 1 from symbols where symbol = 'MA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MAT', 'Mattel Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MAT' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MKC', 'McCormick & Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'MKC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MCD', 'McDonald''s Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'MCD' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MHFI', 'McGraw Hill Financial Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'MHFI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MCK', 'McKesson Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'MCK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MJN', 'Mead Johnson Nutrition Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'MJN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MDT', 'Medtronic plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'MDT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MRK', 'Merck & Co Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'MRK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MET', 'Metlife Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'MET' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KORS', 'Michael Kors Holdings Ltd', 'NYSE' where not exists (select 1 from symbols where symbol = 'KORS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MCHP', 'Microchip Technology Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MCHP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MU', 'Micron Technology Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MU' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MSFT', 'Microsoft Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MSFT' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MHK', 'Mohawk Industries Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'MHK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TAP', 'Molson Coors Brewing Co B', 'NYSE' where not exists (select 1 from symbols where symbol = 'TAP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MDLZ', 'Mondelez International Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MDLZ' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MON', 'Monsanto Co.', 'NYSE' where not exists (select 1 from symbols where symbol = 'MON' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MNST', 'Monster Beverage Corp New', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MNST' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'MCO', 'Moody''s Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'MCO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MS', 'Morgan Stanley', 'NYSE' where not exists (select 1 from symbols where symbol = 'MS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MOS', 'Mosaic Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'MOS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MSI', 'Motorola Solutions Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'MSI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MUR', 'Murphy Oil Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'MUR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'MYL', 'Mylan NV', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'MYL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NKE', 'NIKE Inc B', 'NYSE' where not exists (select 1 from symbols where symbol = 'NKE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NRG', 'NRG Energy', 'NYSE' where not exists (select 1 from symbols where symbol = 'NRG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NDAQ', 'Nasdaq OMX Group/The', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NDAQ' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NOV', 'National Oilwell Varco Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'NOV' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NAVI', 'Navient Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NAVI' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NTAP', 'NetApp Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NTAP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NFLX', 'NetFlix Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NFLX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NWL', 'Newell Rubbermaid Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'NWL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NFX', 'Newfield Exploration Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'NFX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NEM', 'Newmont Mining Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'NEM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NWSA', 'News Corporation', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NWSA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NEE', 'NextEra Energy Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'NEE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NLSN', 'Nielsen NV', 'NYSE' where not exists (select 1 from symbols where symbol = 'NLSN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NI', 'Nisource Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'NI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NBL', 'Noble Energy Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'NBL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'JWN', 'Nordstrom Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'JWN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NSC', 'Norfolk Southern Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'NSC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NTRS', 'Northern Trust Corp (IL)', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NTRS' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'NOC', 'Northrop Grumman Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'NOC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NUE', 'Nucor Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'NUE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'NVDA', 'Nvidia Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'NVDA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ORLY', 'O''Reilly Automotive', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ORLY' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'OKE', 'ONEOK Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'OKE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'OXY', 'Occidental Petroleum', 'NYSE' where not exists (select 1 from symbols where symbol = 'OXY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'OMC', 'Omnicom Group', 'NYSE' where not exists (select 1 from symbols where symbol = 'OMC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ORCL', 'Oracle Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'ORCL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'OI', 'Owens-Illinois Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'OI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PCAR', 'PACCAR Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'PCAR' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'PCG', 'PG&E Corporation', 'NYSE' where not exists (select 1 from symbols where symbol = 'PCG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PNC', 'PNC Finl Services Group', 'NYSE' where not exists (select 1 from symbols where symbol = 'PNC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PPG', 'PPG Industries Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PPG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PPL', 'PPL Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'PPL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PVH', 'PVH Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'PVH' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PLL', 'Pall Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'PLL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PH', 'Parker-Hannifin Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'PH' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PDCO', 'Patterson Cos Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'PDCO' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'PYPL', 'PayPal Holdings Inc.', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'PYPL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'PAYX', 'Paychex Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'PAYX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'PNR', 'Pentair PLC', 'NYSE' where not exists (select 1 from symbols where symbol = 'PNR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PBCT', 'People''s United Financial Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'PBCT' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'POM', 'Pepco Holdings Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'POM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PEP', 'PepsiCo Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PEP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PKI', 'PerkinElmer Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PKI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PRGO', 'Perrigo Company plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PRGO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PFE', 'Pfizer Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PFE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PM', 'Philip Morris International', 'NYSE' where not exists (select 1 from symbols where symbol = 'PM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PSX', 'Phillips 66', 'NYSE' where not exists (select 1 from symbols where symbol = 'PSX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PNW', 'Pinnacle West Capital (AZ)', 'NYSE' where not exists (select 1 from symbols where symbol = 'PNW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PXD', 'Pioneer Natural Resources', 'NYSE' where not exists (select 1 from symbols where symbol = 'PXD' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PBI', 'Pitney Bowes Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PBI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PCL', 'Plum Creek Timber Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'PCL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PX', 'Praxair Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PCP', 'Precision Castparts Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'PCP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PFG', 'Principal Financial Group', 'NYSE' where not exists (select 1 from symbols where symbol = 'PFG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PLD', 'ProLogis Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PLD' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PG', 'Procter & Gamble', 'NYSE' where not exists (select 1 from symbols where symbol = 'PG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PGR', 'Progressive Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'PGR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PRU', 'Prudential Financial Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PRU' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PEG', 'Public Service Enterprise Grp', 'NYSE' where not exists (select 1 from symbols where symbol = 'PEG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PSA', 'Public Storage', 'NYSE' where not exists (select 1 from symbols where symbol = 'PSA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'PHM', 'Pulte Group Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PHM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'QCOM', 'QUALCOMM Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'QCOM' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'QRVO', 'Qorvo, Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'QRVO' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'PWR', 'Quanta Services Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'PWR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'DGX', 'Quest Diagnostics', 'NYSE' where not exists (select 1 from symbols where symbol = 'DGX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'RL', 'Ralph Lauren Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'RL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'RRC', 'Range Resources Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'RRC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'RTN', 'Raytheon Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'RTN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'O', 'Realty Income Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'O' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'RHT', 'Red Hat Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'RHT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'REGN', 'Regeneron Pharmaceuticals Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'REGN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'RF', 'Regions Financial Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'RF' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'RSG', 'Republic Services Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'RSG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'RAI', 'Reynolds American Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'RAI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'RHI', 'Robert Half Intl Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'RHI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ROK', 'Rockwell Automation Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ROK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'COL', 'Rockwell Collins', 'NYSE' where not exists (select 1 from symbols where symbol = 'COL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ROP', 'Roper Technologies, Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ROP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ROST', 'Ross Stores Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ROST' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'RCL', 'Royal Caribbean Cruises Ltd', 'NYSE' where not exists (select 1 from symbols where symbol = 'RCL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'R', 'Ryder System Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'R' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SCG', 'SCANA Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'SCG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SLG', 'SL Green Realty Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'SLG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'CRM', 'Salesforce.com', 'NYSE' where not exists (select 1 from symbols where symbol = 'CRM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SNDK', 'SanDisk Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SNDK' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'HSIC', 'Schein Henry Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'HSIC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SLB', 'Schlumberger Ltd', 'NYSE' where not exists (select 1 from symbols where symbol = 'SLB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SCHW', 'Schwab Charles Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'SCHW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SNI', 'Scripps Networks Interactive', 'NYSE' where not exists (select 1 from symbols where symbol = 'SNI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'STX', 'Seagate Technology', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'STX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SEE', 'Sealed Air Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'SEE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SRE', 'Sempra Energy', 'NYSE' where not exists (select 1 from symbols where symbol = 'SRE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SHW', 'Sherwin-Williams Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'SHW' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SIAL', 'Sigma-Aldrich Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SIAL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SIG', 'Signet Jewelers Ltd', 'NYSE' where not exists (select 1 from symbols where symbol = 'SIG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SPG', 'Simon Property Group', 'NYSE' where not exists (select 1 from symbols where symbol = 'SPG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SWKS', 'Skyworks Solutions Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SWKS' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SJM', 'Smucker J.M. Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'SJM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SNA', 'Snap On Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'SNA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SO', 'Southern Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'SO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'LUV', 'Southwest Airlines Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'LUV' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SWN', 'Southwestern Energy Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'SWN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SE', 'Spectra Energy Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'SE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'STJ', 'St Jude Medical Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'STJ' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SWK', 'Stanley Black & Decker', 'NYSE' where not exists (select 1 from symbols where symbol = 'SWK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SPLS', 'Staples Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SPLS' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SBUX', 'Starbucks Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SBUX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'HOT', 'Starwood Hotel & Resort World', 'NYSE' where not exists (select 1 from symbols where symbol = 'HOT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'STT', 'State Street Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'STT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SRCL', 'Stericycle Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SRCL' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SYK', 'Stryker Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'SYK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'STI', 'SunTrust Banks Inc (GA)', 'NYSE' where not exists (select 1 from symbols where symbol = 'STI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'SYMC', 'Symantec Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'SYMC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'SYY', 'Sysco Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'SYY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TROW', 'T Rowe Price Group Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TROW' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'TEL', 'TE Connectivity Ltd.', 'NYSE' where not exists (select 1 from symbols where symbol = 'TEL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TE', 'TECO Energy Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'TE' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TGNA', 'TEGNA Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'TGNA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TJX', 'TJX Cos Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'TJX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TGT', 'Target Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'TGT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'THC', 'Tenet Healthcare', 'NYSE' where not exists (select 1 from symbols where symbol = 'THC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TDC', 'Teradata Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'TDC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TSO', 'Tesoro Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'TSO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TXN', 'Texas Instruments Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TXN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'TXT', 'Textron Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'TXT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ADT', 'The ADT Corp.', 'NYSE' where not exists (select 1 from symbols where symbol = 'ADT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'BK', 'The Bank of New York Mellon Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'BK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'KHC', 'The Kraft Heinz Company', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'KHC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'PCLN', 'The Priceline Group Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'PCLN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'WMB', 'The Williams Companies Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'WMB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TMO', 'Thermo Fisher Scientific', 'NYSE' where not exists (select 1 from symbols where symbol = 'TMO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TIF', 'Tiffany & Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'TIF' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TWC', 'Time Warner Cable Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'TWC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TWX', 'Time Warner Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'TWX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TMK', 'Torchmark Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'TMK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TSS', 'Total System Services Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'TSS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TSCO', 'Tractor Supply Co', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TSCO' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'RIG', 'Transocean Ltd', 'NYSE' where not exists (select 1 from symbols where symbol = 'RIG' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TRV', 'Travelers Cos Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'TRV' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TRIP', 'TripAdvisor Inc.', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'TRIP' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'FOXA', 'Twenty-First Century Fox, Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'FOXA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'TYC', 'Tyco Intl', 'NYSE' where not exists (select 1 from symbols where symbol = 'TYC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'TSN', 'Tyson Foods Inc A', 'NYSE' where not exists (select 1 from symbols where symbol = 'TSN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'USB', 'US Bancorp', 'NYSE' where not exists (select 1 from symbols where symbol = 'USB' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'UA', 'Under Armour Inc A', 'NYSE' where not exists (select 1 from symbols where symbol = 'UA' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'UNP', 'Union Pacific Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'UNP' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'UPS', 'United Parcel Service Inc B', 'NYSE' where not exists (select 1 from symbols where symbol = 'UPS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'URI', 'United Rentals Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'URI' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'UTX', 'United Technologies Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'UTX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'UNH', 'Unitedhealth Group Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'UNH' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'UHS', 'Universal Health Services B', 'NYSE' where not exists (select 1 from symbols where symbol = 'UHS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'UNM', 'Unum Group', 'NYSE' where not exists (select 1 from symbols where symbol = 'UNM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'URBN', 'Urban Outfitters', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'URBN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'VFC', 'VF Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'VFC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'VLO', 'Valero Energy Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'VLO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'VAR', 'Varian Medical Systems Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'VAR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'VTR', 'Ventas Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'VTR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'VRSN', 'VeriSign Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'VRSN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'VZ', 'Verizon Communications Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'VZ' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'VRTX', 'Vertex Pharmaceuticals Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'VRTX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'VIAB', 'Viacom Inc B', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'VIAB' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'V', 'Visa Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'V' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'VNO', 'Vornado Realty Trust', 'NYSE' where not exists (select 1 from symbols where symbol = 'VNO' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'VMC', 'Vulcan Materials Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'VMC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WEC', 'WEC Energy Group Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'WEC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WMT', 'Wal-Mart Stores', 'NYSE' where not exists (select 1 from symbols where symbol = 'WMT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WBA', 'Walgreens Boots Alliance Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'WBA' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'DIS', 'Walt Disney Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'DIS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WM', 'Waste Management Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'WM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WAT', 'Waters Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'WAT' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WFC', 'Wells Fargo & Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'WFC' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WRK', 'WestRock Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'WRK' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WDC', 'Western Digital Corp', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'WDC' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'WU', 'Western Union Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'WU' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WY', 'Weyerhaeuser Co', 'NYSE' where not exists (select 1 from symbols where symbol = 'WY' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WHR', 'Whirlpool Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'WHR' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WFM', 'Whole Foods Market Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'WFM' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'WYN', 'Wyndham Worldwide Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'WYN' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'WYNN', 'Wynn Resorts Ltd', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'WYNN' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'XL', 'XL Group Plc', 'NYSE' where not exists (select 1 from symbols where symbol = 'XL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'XEL', 'Xcel Energy Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'XEL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'XRX', 'Xerox Corp', 'NYSE' where not exists (select 1 from symbols where symbol = 'XRX' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'XLNX', 'Xilinx Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'XLNX' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'XYL', 'Xylem Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'XYL' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'YHOO', 'Yahoo Inc', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'YHOO' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'YUM', 'Yum! Brands Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'YUM' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ZBH', 'Zimmer Biomet Holdings Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ZBH' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'ZION', 'Zions Bancorp (UT)', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'ZION' and exchange = 'NASDAQ OMX');
insert into symbols (symbol, company_name, exchange) select 'ZTS', 'Zoetis Inc', 'NYSE' where not exists (select 1 from symbols where symbol = 'ZTS' and exchange = 'NYSE');
insert into symbols (symbol, company_name, exchange) select 'EBAY', 'eBay Inc.', 'NASDAQ OMX' where not exists (select 1 from symbols where symbol = 'EBAY' and exchange = 'NASDAQ OMX');

commit;
